create extension if not exists pgcrypto;

create or replace function public.handle_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  email text not null unique,
  display_name text,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  category text not null default '공지사항' check (category in ('공지사항', '센터소식', '홍보')),
  pinned boolean not null default false,
  views integer not null default 0,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.home_feeds (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null default '',
  category text not null default 'Notice' check (category in ('Program', 'Education', 'Notice', 'Column')),
  tags text[] not null default '{}'::text[],
  image_url text not null,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.site_media (
  key text primary key,
  image_url text not null,
  updated_at timestamptz not null default timezone('utc'::text, now())
);

drop trigger if exists notices_set_updated_at on public.notices;
create trigger notices_set_updated_at
before update on public.notices
for each row
execute function public.handle_updated_at();

drop trigger if exists home_feeds_set_updated_at on public.home_feeds;
create trigger home_feeds_set_updated_at
before update on public.home_feeds
for each row
execute function public.handle_updated_at();

drop trigger if exists site_media_set_updated_at on public.site_media;
create trigger site_media_set_updated_at
before update on public.site_media
for each row
execute function public.handle_updated_at();

alter table public.admin_users enable row level security;
alter table public.notices enable row level security;
alter table public.home_feeds enable row level security;
alter table public.site_media enable row level security;

drop policy if exists "Public read notices" on public.notices;
create policy "Public read notices"
on public.notices
for select
using (true);

drop policy if exists "Public read home feeds" on public.home_feeds;
create policy "Public read home feeds"
on public.home_feeds
for select
using (true);

drop policy if exists "Public read site media" on public.site_media;
create policy "Public read site media"
on public.site_media
for select
using (true);

insert into storage.buckets (id, name, public)
values
  ('notices', 'notices', true),
  ('home-feed', 'home-feed', true),
  ('site-media', 'site-media', true)
on conflict (id) do nothing;

drop policy if exists "Public read notice images" on storage.objects;
create policy "Public read notice images"
on storage.objects
for select
using (bucket_id = 'notices');

drop policy if exists "Public read home feed images" on storage.objects;
create policy "Public read home feed images"
on storage.objects
for select
using (bucket_id = 'home-feed');

drop policy if exists "Public read site media images" on storage.objects;
create policy "Public read site media images"
on storage.objects
for select
using (bucket_id = 'site-media');

comment on table public.admin_users is 'Supabase Auth 사용자 중 관리자 권한을 가진 계정 목록';
